Update pileline yaml

diff --git a/.github/workflows/pylint.yml b/.github/workflows/pylint.yml
--- a/.github/workflows/pylint.yml
+++ b/.github/workflows/pylint.yml
@@ -1,41 +1,42 @@
-name: Lint Code with Pylint
+name: Pylint
 
-on:
-  push:
-    branches:
-      - main  # Run on pushes to the main branch
-  pull_request:  # Run on pull requests to ensure code quality
-    branches:
-      - main
+on: [push]
 
 jobs:
-  lint:
+  build:
     runs-on: ubuntu-latest
     strategy:
       matrix:
         python-version: ["3.11"]
     steps:
-      # Step 1: Checkout the repository
-      - name: Checkout repository
-        uses: actions/checkout@v4
-      
-      # Step 2: Set up the Python environment
-      - name: Set up Python ${{ matrix.python-version }}
-        uses: actions/setup-python@v3
-        with:
-          python-version: ${{ matrix.python-version }}
+    - uses: actions/checkout@v4
 
-      # Step 3: Install dependencies and Pylint
-      - name: Install dependencies and Pylint
-        run: |
-          python -m pip install --upgrade pip
-          python -m venv venv
-          source venv/bin/activate
-          pip install -r requirements.txt
-          pip install pylint
+    - name: Set up Python ${{ matrix.python-version }}
+      uses: actions/setup-python@v3
+      with:
+        python-version: ${{ matrix.python-version }}
 
-      # Step 4: Run Pylint
-      - name: Run Pylint on Python files
-        run: |
-          source venv/bin/activate
-          pylint $(git ls-files '*.py')
+    - name: Install dependencies
+      run: |
+        python -m pip install --upgrade pip
+        python -m venv venv
+        source venv/bin/activate
+        pip install -r requirements.txt
+        pip install pylint pylint-json2html
+
+    - name: Run Pylint and check score
+      run: |
+        pylint --output-format=json $(git ls-files '*.py') > pylint_output.json || true
+        
+        # Extract the score from the pylint_output.json
+        pylint_score=$(jq '[.[] | .score] | add / length' pylint_output.json)
+        echo "Pylint score: $pylint_score"
+
+        # If the score is greater than or equal to 8, exit with code 0, otherwise exit with 1
+        if (( $(echo "$pylint_score >= 8" | bc -l) )); then
+          echo "Pylint score is above 8, passing the build."
+          exit 0
+        else
+          echo "Pylint score is below 8, failing the build."
+          exit 1
+        fi
